name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install modules
        run: yarn install
      - name: Fix Problem
        run: npx browserslist@latest --update-db
      - name: Build project
        run: yarn build
      - name: Test
        run: yarn test -o --watch
