name: Verificar el código
on:
  pull_request:
    branches:
      - master
jobs:
  test:
    name: Verificar el código
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install packages
        run: yarn install
      - name: Prettier
        run: npm run format
      - name: Lint
        run: npm run lint
